### ISSUE TITLE
Error initializing EDA with data.

### ISSUE THREAD

**Issue by DaniConZo** [VicentePerezSoloviev/EDAspy#13]
When starting EDA with data, an error message appears indicating that the lower_bound and upper_bound parameters are missing (which are used in case initial data is not used).
![Init-data issue](https://github.com/VicentePerezSoloviev/EDAspy/assets/137918027/8a04e0ce-d4eb-43e7-b44e-88ec0daae4a6)

**Comment by VicentePerezSoloviev** [comment]
Hi @DaniConZo . Thank you for you contribution. I have just pushed a modification to the EDA implementation so it is no longer mandatory to set lower and upper bound. If it is set, it is considered. If it is not, then there is a pre-fixed value. See this.

https://github.com/VicentePerezSoloviev/EDAspy/blob/f5fd52be374fa510db4da73bf5cf5eb6fb55c3d0/EDAspy/optimization/multivariate/egna.py#L54

If you download from source the new project, it should be fixed. Thanks you.
