### ISSUE TITLE
Why CategoricalSampling doesn't use self.frequency?

### ISSUE THREAD

**Issue by MrJake222** [VicentePerezSoloviev/EDAspy#14]
https://github.com/VicentePerezSoloviev/EDAspy/blob/f5fd52be374fa510db4da73bf5cf5eb6fb55c3d0/EDAspy/optimization/custom/initialization_models/categorical_geninit.py#L32-L46

**Comment by VicentePerezSoloviev** [comment]
Thank you for pointing this out. This is a bug that has been moved from the samplers. It is defined in order to ensure the initial probabilities of each possible instance. Will go through it and solve this. Thanks.

**Comment by VicentePerezSoloviev** [comment]
Checkout the new version in https://github.com/VicentePerezSoloviev/EDAspy/blob/master/EDAspy/optimization/custom/initialization_models/categorical_geninit.py

Now the initializer has been updated.

**Comment by VicentePerezSoloviev** [comment]
The issue has been solved
