### ISSUE TITLE
The time consumption of SPEDA

### ISSUE THREAD

**Issue by marcoboll** [VicentePerezSoloviev/EDAspy#23]
The SPEDAis an excellent and innovative work in EDAs domain. I want to express my appreciation for your work, which I intend to apply to my own projects. However, I've encountered some performance issues when using your EDAspy.

While I found that for smaller values of L, such as L=1, the CPU time results were similar to those you provided in your GitHub repository, I noticed significant slowdowns when setting L to larger values, such as L=15 (as specified in your paper). With a population size of 300 and 50 iterations, the algorithm's runtime approached nearly 30 minutes.

I've tried using different machines, but the results remain consistent. I would like to inquire about the possible reasons for this performance degradation. Is it due to the algorithm itself? How might I modify the implementation to improve the execution time?

I look forward to your response.

**Comment by VicentePerezSoloviev** [comment]
Hello @marcoboll . First of all thank you for using EDAspy and for your input. 

SPEDA is an EDA variant in which semiparametric Bayesian networks are used in each iteration. Moreover, the L parameter that you mention regards the number of previous interactions considered. L=1 will perform as a normal evolutionary algorithm. With L>1 we have an archive-based approach. L=2, for example will use the best solutions from t-1 and t-2 to train the Bayesian network at iteration t. The higher is L, the more solutions are considered in the learning process of the BN. Thus, it makes sense to slow down the computation (we also experienced this issue during the experimentation), but we expect a less probable "early convergence" to local optima. 

In order to speed up you computation I would suggest the following items:
- Use the parallelization option of the EDA so you can parallelize the solutions evaluation.
- Decrease the population size.
- Decrease the truncation size.
- Decrease the archive length (L).
- If you are looking for a faster algorithm, but still multivariate and with good performance, I would suggest you to use EGNA approach.

Hope to have solved you questions with this answer. Please, let me know if you have any more concerns. All the best,
Vicente P. Soloviev

**Comment by marcoboll** [comment]
Dear Vicente P. Soloviev,

Thank you for your response. If I adhere to the experimental setup outlined in the paper, it appears that optimizing a problem with SPEDA on the CEC2014 benchmark at 50 dimensions will take over a day. Therefore, using SPEDA as a comparison algorithm is not feasible from a time perspective. However, the paper indicates that only one hour is required to optimize a problem at 50 dimensions. I use better CPU and GPU, but it takes more time. I would like to know why there is such a significant discrepancy in time costs. What steps can I take to achieve a similar time expenditure as reported in your paper?

Looking forward to your response.

**Comment by VicentePerezSoloviev** [comment]
Hello again,
The paper shows an average CPU time for all the experiments run in the experimentation. For D=50, the experiment setup allows to do  10000D fitness evaluations. Considering the population size of 300, we have around 1670 iterations. I have just run it in my personal laptop (different device to the one used for the experimentation). Please, find here attached the CPU time used for the computations. As you can see, it is quite similar (a bit higher as a worse machine is being used) to the one shown in the paper. 

![screenshot](https://github.com/user-attachments/assets/92bc6c4f-9827-41c0-95b9-cf969ac6c522)

Some things that may be slowing down your experimentation:
- Are you running other algorithms in parallel?
- Are you running NON-independent executions of the algorithm? I suggest you to define a script which executes and outputs the results from the algorithm. If you run SPEDA several times, then several times the script should be called. Avoid doing loops and colling in the same script, as this may be generating some rubbish files...
- Are you correctly defining the parameter configurations?
- The files needed for the cost function computation are located in an easy and fast accessible location in your computer?
- Please, check the tutorials provided in the library and check if you are correctly defining the implementation.

Other than this, I cannot understand why you experimentation is running so slow. May I see how are you implementing the code? 

All the best,
Vicente

**Comment by marcoboll** [comment]
> Hello again, The paper shows an average CPU time for all the experiments run in the experimentation. For D=50, the experiment setup allows to do 10000D fitness evaluations. Considering the population size of 300, we have around 1670 iterations. I have just run it in my personal laptop (different device to the one used for the experimentation). Please, find here attached the CPU time used for the computations. As you can see, it is quite similar (a bit higher as a worse machine is being used) to the one shown in the paper.
> 
> ![screenshot](https://private-user-images.githubusercontent.com/44190633/371543096-92bc6c4f-9827-41c0-95b9-cf969ac6c522.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDMwODYsIm5iZiI6MTcyNzQ0Mjc4NiwicGF0aCI6Ii80NDE5MDYzMy8zNzE1NDMwOTYtOTJiYzZjNGYtOTgyNy00MWMwLTk1YjktY2Y5NjlhYzZjNTIyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEzMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZGU2Y2Y2NTQ1Y2RhMjNmYzZhM2ExOGUyNTQ4ZDQ3ZDk3ZDEwNGMwMjRhZjkxOTc0MWFmMWQ5NDNlNmExZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.omBWBv3kQzvkKyup816H2XnVez0cxPDUk6vpwtux7sQ)
> 
> Some things that may be slowing down your experimentation:
> 
> * Are you running other algorithms in parallel?
> * Are you running NON-independent executions of the algorithm? I suggest you to define a script which executes and outputs the results from the algorithm. If you run SPEDA several times, then several times the script should be called. Avoid doing loops and colling in the same script, as this may be generating some rubbish files...
> * Are you correctly defining the parameter configurations?
> * The files needed for the cost function computation are located in an easy and fast accessible location in your computer?
> * Please, check the tutorials provided in the library and check if you are correctly defining the implementation.
> 
> Other than this, I cannot understand why you experimentation is running so slow. May I see how are you implementing the code?
> 
> All the best, Vicente

Dear,
Thanks for your reply! This is the implementing code:

import numpy as np
from time import process_time

from EDAspy.optimization import EMNA, EGNA, SPEDA, UMDAc, MultivariateKEDA, UnivariateKEDA, PBIL, BOA
from EDAspy.benchmarks import ContinuousBenchmarkingCEC14
n = 50
max_it = 50
dead_it = max_it
l = 15
alpha = 0.4
size_gen = 300

bench = ContinuousBenchmarkingCEC14(n)

speda = SPEDA(size_gen=size_gen, max_iter=max_it, dead_iter=dead_it, n_variables=n, lower_bound=-100, upper_bound=100, l=l)
start_time = process_time()
result_speda = speda.minimize(bench.cec14_1, True)
speda_time = process_time() - start_time
print('Best cost:', result_speda.best_cost, '\tTime:', speda_time)




This is the result of this code. It consume  24528 seconds.
![time](https://github.com/user-attachments/assets/87cd1053-ae88-4fbe-b646-9a41abd7d9aa)

I installed EDAspy using the Git, and I believe there are no problem  with the code as the program runs without any errors or warnings. I think it's more likely that the problem lies with the running environment.

best regard,
Marco

**Comment by VicentePerezSoloviev** [comment]
According to the implementation that you have just posted, everything seems to be okay. Some suggestions:
- For 50 variables you should use a higher number of iterations, to allow the convergence of the EDA.
- You can print the CPU time from result_speda.

As you suggest I´d try changing the running environment. This is out of EDAspy´s control, so let me close this issue.
